language: java
sudo: true
dist: trusty
jdk: oraclejdk8
addons:
  sonarcloud:
    organization: "tijn167-github" # the key of the org you chose at step #3
  apt:
    packages:
      - oracle-java8-installer
before_install:
  - chmod +x mvnw
install:
- mvn install
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
